### ISSUE TITLE
OT is not defined (core.js - line 76)

### ISSUE THREAD

**Issue by mattwebdev** [opentok/accelerator-sample-apps-js#13]
### General information

- Library version(s):     "opentok-accelerator-core": ">=2.0.0",
- iOS/Android/Browser version(s): All Browsers
- Devices/Simulators/Machine affected: All Browsers
- Reproducible in the demo project? (Yes/No): YES

## Bug report
when running the React Accellerator app, an error of OT is not defined (core.js - line 76) happens. after digging through core.js -- OT is not defined anywhere.

**Comment by maikthomas** [comment]
Hi @mattwebdev, 
sorry to hear you're having issues.
 `OT` comes from the opentok.js library: https://tokbox.com/developer/sdks/js/reference/OT.html
In the React App, this library is added using a script tag in index.html here: https://github.com/opentok/accelerator-sample-apps-js/blob/master/react-sample-app/public/index.html#L7

I tried setting this app up from scratch:
- cloning the repo
- installing npm modules
- adding the config.json file
- running `npm start`

and everything worked fine. Have you removed that line or touched `index.html` in any way?

Thanks,
Mike

**Comment by maikthomas** [comment]
I’m closing this issue because it has been inactive for a few weeks. This probably means that it is not reproducible or it has been fixed.

Please reopen if you still encounter this issue You can also contribute directly by providing a patch.

Thank you!

**Comment by Jagdeep-Sing** [comment]
@maikthomas  please help!! :  https://github.com/opentok/accelerator-sample-apps-js/issues/18
