### ISSUE TITLE
Can't parse the data of otCore.state() object

### ISSUE THREAD

**Issue by Jagdeep-Sing** [opentok/accelerator-sample-apps-js#20]
Hi, the accelerator-sample-apps are very helpful.
I'm using vanilla-js sample app and want to add image capture feature in it and for that I have [THIS](https://tokbox.com/developer/guides/customize-ui/js/#video_snapshot).
But,  when I called `otCore.state()` this returned a object and for capture, we need to parse:

> obj > subscribers > camera > DYNAMIC SUBSCRIBER > getImgData()

obj.subscribers.camera I'm parsing successfully but unable to parse next Dynamic subscriber id(its changing every time). then I try to do like `subscribers.camera[0]` . this also gives error.

 Here is a screen shot of data that this object returning : 
In this SS I'm testing with publishers object.
![selection_031](https://user-images.githubusercontent.com/25609915/36413102-f414d7f0-1642-11e8-8d4e-e20011ead8ea.png)

It sometimes gives cyclic object error then I serialize the object but after serializing, some keys and values missed.
_help wanted._ @maikthomas

**Comment by maikthomas** [comment]
Hi @Jagdeep-Sing,
Doing `subscribers.camera[0]` won't work because camera is an object, not an array. You could do something like this:
```
const cameraIds = Object.keys(state.subscribers.camera);
let cameraId;
let imageData;
if (cameraIds.length > 0) {
   cameraId = cameraIds[0];
   imageData = state.subscribers.camera[cameraId].getImgData();
}
```
or perhaps use a library like underscore: http://underscorejs.org/#values

**Comment by maikthomas** [comment]
There doesn't appear to be an issue here so closing, feel free to comment if you feel this isn't resolved.
@Jagdeep-Sing 'how-to' questions of this nature are better suited to stackoverflow where more people will see them. Just be sure to tag the questions with `opentok` or `tokbox`.
Thanks,
Mike

**Comment by Jagdeep-Sing** [comment]
Thanks mikeThomas, your snippet solved the problem. Yes sure I can post
there but SO people are very very rude. They will close it or make it
duplicate without any knowledge. The worst egoist people are there with
high repo.

**Comment by maikthomas** [comment]
I'm sorry to hear that @Jagdeep-Sing,
I've always had a very positive experience with SO, you might want to consider familiarising yourself with their best practice guide: https://stackoverflow.com/help/how-to-ask in order to get a better response from the community.
Best of luck,
Mike
