### ISSUE TITLE
Unhandled Rejection (OT_AUTHENTICATION_ERROR): Invalid token format (1004)

### ISSUE THREAD

**Issue by hayreddintuzel** [opentok/accelerator-sample-apps-js#21]
I am trying npm run start command, but I am encountering " Unhandled Rejection (OT_AUTHENTICATION_ERROR): Invalid token format (1004)  " error. I checked apikey, sessionId and token multiple times, but alwasy same error goes on.

Note: I am trying on React js

**Comment by maikthomas** [comment]
Hi @hayreddintuzel,
The error says `Invalid token format` so I think we can forget about apikey and sessionId for now.
How are you generating this token? Could you try generating it again?
Is there any more to the error message?
Thanks,
Mike

**Comment by hayreddintuzel** [comment]
Yes, I regenerate it again. But same issue goes on

**Comment by maikthomas** [comment]
How are you generating this token? 
Is there any more to the error message / stack trace?

**Comment by hayreddintuzel** [comment]
I am generating maually from dashboard. No, I have not error while generating. But I will give up using tokbox.

**Comment by maikthomas** [comment]
@hayreddintuzel I was able to reproduce this if I remove the `T1==` part from my token.
Have you ensured the full token is copied including the `T1==` at the start and `==` at the end?

**Comment by Jagdeep-Sing** [comment]
@hayreddintuzel  This happen only if your tokbox account is paused, you need to choose a plan to continue or login with different account.
