### ISSUE TITLE
Screen Sharing Issue

### ISSUE THREAD

**Issue by vnaveed** [opentok/accelerator-sample-apps-js#27]
When we click on screen sharing icon, screen  keep on mirroring itself. 

Can some one help me on this.

![image](https://user-images.githubusercontent.com/49260074/59857002-a4743480-9395-11e9-8e8a-ac6da811fc99.png)

![image](https://user-images.githubusercontent.com/49260074/59857045-bce44f00-9395-11e9-8fd0-5fe6ef0b0d34.png)

**Comment by marcmetz** [comment]
That's the "hall of mirrors" effect. 

Read [here](https://tokbox.com/developer/guides/screen-sharing/js/#maximum-resolution) how to prevent it.
